### ISSUE TITLE
erreur timelog

### ISSUE THREAD

**Issue by xavier-rognon** [RedBoardDev/EpitechIntranetStatistics#1]
dans l'onglet timelog on voit que 6 jours alors que le timelog est calculé sur sept

**Comment by RedBoardDev** [comment]
> dans l'onglet timelog on voit que 6 jours alors que le timelog est calculé sur sept

Peut tu mettre à jour le projet, et reproduire de nouveau ? S'il y a encore ce bug, peut-tu me faire un screenshoot du bug ?
