### ISSUE TITLE
Affichage du Tépitech

### ISSUE THREAD

**Issue by racso27th** [RedBoardDev/EpitechIntranetStatistics#12]
Bonsoir 
Je suis en Tek1
Je viens d'ouvrir l'onglet et j'ai remarqué que la valeur de mon tépitech était à 0 or ce n'est pas le cas.
Pourriez vous corriger ce bug

Par ailleurs , le cas des projets qui se chevauchent dans le modules d'anglais n'est pas correctement géré.
Je suis inscrit à un des projets de ce module et celui ci n'apparait pas.

**Comment by RedBoardDev** [comment]
Bonjour,

Il me faut plus de précision afin de pouvoir reproduire le bug. De quand date ce tepitech ? Quel était le type de tepitech (self-assessment, tepitech,...) ? Est-ce que cela concerne tout vos tepitechs ou uniquement un seul ?

N'hésitez pas à fournir des screenshots, cela aiderait aussi à comprendre plus facilement. Je n'ai encore jamais relevé de problème dans les modules d'anglais de mon coté.

**Comment by RaphxelS** [comment]
Bonjour,
Meme probleme ici (tech2), le tepitech etait bien affiché avant cela.
C'etait le 1er tepitech de l'année
![image](https://github.com/RedBoardDev/EpitechIntranetStatistics/assets/100469363/5e18aa2e-aa90-4e95-8707-69f44f6df2bc)
![image](https://github.com/RedBoardDev/EpitechIntranetStatistics/assets/100469363/cffe4746-2968-44dc-be41-439001fa85f9)

**Comment by racso27th** [comment]
![Screenshot from 2024-04-27 15-54-44](https://github.com/RedBoardDev/EpitechIntranetStatistics/assets/146736715/42c43572-6862-49a0-9c8f-dc9c29a248d3)
Voila en ce qui concerne mon tépitech
![Screenshot from 2024-04-27 15-54-44](https://github.com/RedBoardDev/EpitechIntranetStatistics/assets/146736715/a61f5310-867f-4485-b175-cde7f6318275)

**Comment by racso27th** [comment]
![Uploading im_tec.png…]()

Voila ce que ce qui est affiché
![Screenshot from 2024-04-27 15-56-31](https://github.com/RedBoardDev/EpitechIntranetStatistics/assets/146736715/b7cb539c-8f5d-4a7a-b557-287762fbe3c7)
Et voilà ce que j'ai

Et pour ce qui concerne les projets d'anglais ,je suis inscrit au projet "Pitch your vidéo game for investor funding"

![Screenshot from 2024-04-27 16-08-19](https://github.com/RedBoardDev/EpitechIntranetStatistics/assets/146736715/b1d65849-8190-42d8-8079-4a76f33ddb6e)

Sauf que les seuls projets qui sont là sont "Get that Intership" ( 1er projet )  et "Plan an Epitech Trip Abroad" (3eme projet)
