### ISSUE TITLE
XP mal comptabilisé

### ISSUE THREAD

**Issue by Thhundder** [RedBoardDev/EpitechIntranetStatistics#14]
![palantir](https://github.com/RedBoardDev/EpitechIntranetStatistics/assets/146443755/51938284-16b4-4a7d-b4fc-465d3814ac52)
![stat](https://github.com/RedBoardDev/EpitechIntranetStatistics/assets/146443755/96c56681-440d-4f61-b0c1-8bd8861cd7b6)
Je suis censé être à 10xp

**Comment by RedBoardDev** [comment]
Bonjour,
D'où provient le premier screen ? La seul activité HUB est cette game jam ?

**Comment by Thhundder** [comment]
Bonjour,
Le premier screen vient de palantir, l'outil officiel de Epitech pour le hub.
Ma seule activité est bien cette Jam la, qui m'a rapporté 10xp

**Comment by RedBoardDev** [comment]
Le principe de HUB aillant complètement changé, je ferme cette issues, la partie HUB devant être refaite.
