### ISSUE TITLE
Module "Acquis"

### ISSUE THREAD

**Issue by FuniclemDev** [RedBoardDev/EpitechIntranetStatistics#4]
Je viens de finir le premier semestre, et dans le module PCP par exemple j'ai juste Acquis mais normalement 0 crédit car je n'ai fais aucune séance pour obtenir ces 2 crédits, mais je les ai quand même eu.
Bonne journée

---
Epitech Strasbourg
Clément D.

**Comment by RedBoardDev** [comment]
Bonjour,

Un fix devrait être effectué avec la refonte global du projet qui est en cours.
Je fermerais le ticket avec sa sortie, afin que vous puissiez vérifier
