### ISSUE TITLE
Dashboard important feature + bug

### ISSUE THREAD

**Issue by ItsZcx** [RedBoardDev/EpitechIntranetStatistics#6]
The dashboard showing project deadlines is super handy, but it could be even better with a straight line running top to bottom, indicating today's date (or any other form of indication). This would make it much easier to see exactly where we are in time with the projects.

Ex: Todays date is mar 8
![asd](https://github.com/RedBoardDev/EpitechIntranetStatistics/assets/114907868/1b6b5384-44a6-4197-a7fb-2e3385df5262)

Also, the date that are written at the bottom does not seem correct. All the texts such as [MONTH] '24 are behind the others 15 [MONTH]. And it does not make sense that today, Mar 8, is after Mar '24.

**Comment by RedBoardDev** [comment]
For information on the dates, this is correct but rather bizarre I agree. The Mar 24 label is the beginning of March 2024. 24 being the year.

> The label Sep '23 is indicating the start of the month in the year 2023, then followed by 15 Sep, which is the 15th of September. Yes, the default format is very confusing but you can change it:

So I've changed that for a clearer format
