### ISSUE TITLE
Timeline Feedback

### ISSUE THREAD

**Issue by nkurata** [RedBoardDev/EpitechIntranetStatistics#7]
Should create a bar on the timeline to see where you are in your year :)
<img width="914" alt="Screenshot 2024-03-15 at 14 07 45" src="https://github.com/RedBoardDev/EpitechIntranetStatistics/assets/90001579/6d64be39-9ddd-4ac8-8733-d2d7424cb287">

**Comment by RedBoardDev** [comment]
Please report to issue #6
