### ISSUE TITLE
L'affichage onglet HUB

### ISSUE THREAD

**Issue by ChrisG-L** [RedBoardDev/EpitechIntranetStatistics#9]
L'affichage de l'onglet HUB cache les statistiques du haut (sans doute parce que j'ai beaucoup de participations à des Talks).
<img width="1220" alt="HUB" src="https://github.com/RedBoardDev/EpitechIntranetStatistics/assets/146164277/21b8bfb9-9daf-43e1-8e34-89f369e84bfe">

**Comment by RedBoardDev** [comment]
En effet, le problème de responsivité est global sur le layout de la popup. Il faudrait refaire un layout propre qui permettra d'avoir une structure fixe et un contenu movible.

**Comment by ChrisG-L** [comment]
D'acc, sinon très belle nouvelle version. Merci !

**Comment by RedBoardDev** [comment]
Le principe de HUB aillant complètement changé, je ferme cette issues, la partie HUB devant être refaite.
